import { FooterCp } from './components/footer'
import { HeaderCp } from './components/header'
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="robots" content="noindex,nofollow" />
      <body>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
        <HeaderCp />
        {children}
        <FooterCp />
      </body>
    </html>
  )
}
